---
platforms:
  - name: rockylinux8
    image: geerlingguy/docker-rockylinux8-ansible:latest
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /usr/lib/systemd/systemd
