---
- name: Converge
  hosts: all
  vars:
    sources:
      journald:
        type: journald
        current_boot_only: true
    sinks:
      vector:
        type: vector
        inputs: ["journald"]
        address: "vector.example.com:9000"
        healthcheck:
          enabled: false
    vector_install_from_repo: true
  tasks:
    - name: Include role vector
      ansible.builtin.include_role:
        name: telekom_mms.vector.vector
