---
name: molecule
on:
  pull_request:
    branches: ["main", "master", "stable", "release/v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        scenario:
          - debian12
          - rockylinux8
          - rockylinux9
          - ubuntu2204
          - ubuntu2404

    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}"
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_args: --scenario-name ${{ matrix.scenario }}
